### ISSUE TITLE
profile_id credential is required to list profiles

### ISSUE THREAD

**Issue by chazmcgarvey** [denisneuf/python-amazon-ad-api#155]
**Describe the bug**
The library requires a `profile_id` credential to make the `Profiles().list_profiles()` call, but the [API does not require that](https://advertising.amazon.com/API/docs/en-us/guides/get-started/retrieve-profiles#access-the-profiles-resource). Listing profiles is how one might discover profile IDs, so it doesn't make sense to require one.

**To Reproduce**
```
credentials = {
    "client_id": "...",
    "client_secret": "...",
    "refresh_token": "...",
}
result = Profiles(
    credentials=credentials, marketplace=Marketplaces.NA
).list_profiles(
    apiProgram="report",
    accessLevel="view",
)
```

This code throws an `AttributeError`: 'CredentialProvider' object has no attribute 'credentials'.

**Expected behavior**
The `Profiles().list_profiles()` call should not require `profile_id` in the credentials.

**Workaround**
You can provide a dummy value like `"0"` for the `profile_id`. The library does send the `Amazon-Advertising-API-Scope` header and Amazon validates the value during the `/v2/profiles` call (so it must be an integer), but after validation the value is ignored as far as I can tell.

**Comment by denisneuf** [comment]
Hi [chazmcgarvey](https://github.com/chazmcgarvey) first of all, apology for the very late response, but I totally agree with you, in my experience I used the curl instead of the library to list my profiles so I am aware that is a contradiction ask for profiles while you need provide a profile_id but as later almost all the calls to the api need the profile_id I am not sure how to proceed.
About the workaround I understand may work but some users that for mistake do not provide a profile_id if we overwrite with 0 will get an authentication error instead of a missing credentials exception.
Do you have other suggestions?

**Comment by zsichina** [comment]
Hi @denisneuf,

We can separate REQUIRED and ADDITIONAL credentials in `credential_provider.py` (profile_id as an additional) and add flag `verify_additional_credentials` with default value True to Clients __init__ (this will guarantee backward compatibility)

After that in `Profiles` if  `profile_id` will be None, but `verify_additional_credentials=False` request will return correct results.  `profile_id=0` without passing flag will work too.

I can prepare PR for this

**Comment by denisneuf** [comment]
Sorry for the delay, sounds good if you want prepare a PR in that way.

**Comment by zsichina** [comment]
Hi @denisneuf ,
Ready for review -> https://github.com/denisneuf/python-amazon-ad-api/pull/179

sorry for being late on this PR
